### ISSUE TITLE
stuck at colliding and keep crashing when i tryna shoot

### ISSUE THREAD

**Issue by Orca4real** [devloglogan/MultiplayerFPSTutorial#10]
Hello, i already copy your tutorial and when try to debug it keep crashing when i tryna shoot and it keep saying:

E 0:00:03:0929   Player.gd:6 @ _ready(): Node not found: "Camera3D/RayCast3Dnew" (relative to "/root/World/1").
  <C++ Error>    Method/function failed. Returning: nullptr
  <C++ Source>   scene/main/node.cpp:1364 @ get_node()
  <Stack Trace>  Player.gd:6 @ _ready()
                 world.gd:32 @ add_player()
                 world.gd:21 @ _on_host_button_pressed()

**Comment by devloglogan** [comment]
Sorry you've bumped into some problems! However this error is from a mistake you've made somewhere and not an issue of the tutorial. It looks like your raycast is named "RayCast3Dnew" in the onready path, my guess is that this is incorrect and it should just be "RayCast3D". Best of luck!
