### ISSUE TITLE
Does not work with 4.1

### ISSUE THREAD

**Issue by benjamin-kirkbride** [devloglogan/MultiplayerFPSTutorial#12]
There are a bunch of errors / bugs for 4.1, seemingly.

**Comment by devloglogan** [comment]
Just tried out the project on 4.1.1 and it all still runs fine. This UPnP example won't work for every situation, it's just what I've found to be the easiest possible introduction to remote multiplayer. Common issues are if you don't have access to IPv4, UPnP probably won't work. You also will not be able to connect via UPnP with devices connected via the same router. I'll update the readme with some of this info.

If you find specific errors unrelated to this, feel free to let me know. Thanks!
