### ISSUE TITLE
(Multiplayer) Godot 4 - RPG Inventory System From Scratch + Godot_Voxel (Voxelgame Blockygame) Community Demonstration

### ISSUE THREAD

**Issue by WithinAmnesia** [devloglogan/MultiplayerFPSTutorial#13]
I am sorry to ask this here but I do not know how to ask this in a better location and Youtube comments do not have links.

I have been making open source forever free working multiplayer 'big game' systems and demonstrations examples in Godot 4+ for the creative community. Currently I have been making an ~'educational community archive demonstration copy' / testing version of your great RPG inventory, item, chest, pick up and drop, equipment and other foundational RPG data systems tutorial. I have been recently recreating your 'Godot 4 - RPG Inventory System From Scratch' tutorial in Godot 4.2.1.NET+ (via the Voxel_Game engine module 4.2.2.NET+ to be exact) https://www.youtube.com/watch?v=V79YabQZC1s . I got everything to the chest and potions systems working in the exact copy version. Then I felt I had to pause and think more deeply and with more critically about the player items systems after getting the inventory, chest and pick and drop item systems working. I have a big worry now because I feel / think the player items in the great tutorial are not multiplayer compatible with the community open source forever free Godot_Voxel (Voxelgame Blockygame) Community Demonstration: https://github.com/Zylann/voxelgame + https://github.com/Zylann/godot_voxel . I feel I must find help and community guidance to do things properly going beyond the known tutorials, documentation and directions.

I am endeavouring to create an open source and forever free creative community educational foundational game systems demonstration example library. With the main focus being based around a working multiplayer seamless chunk system for Godot 4.2.1.NET. So as for people in the creative community to have open source forever free working game examples to help create big multiplayer games in Godot 4.2.1.NET+. Here are some example goals, work and progress links: https://github.com/WithinAmnesia/ARPG/discussions/16 + https://github.com/Zylann/voxelgame/issues/103 + https://github.com/Zylann/voxelgame/issues/104 
I am at a point where I need to ask for help with the author of the Godot 4 - RPG Inventory System From Scratch tutorial. For there are a lot of details that need to be addressed in order to successfully ~translate / adapt the Godot 4 - RPG Inventory System From Scratch tutorial to work with a community educational implementation for the Godot_Voxel (Voxelgame Blockygame) Community Demonstration. I am a very experienced RPG person who desires to create big games in Godot 4.2.1.NET+. For I have worked on big games for decades 20+ years now and I wish for the community to have the tools they need to make big games forever free. I have a lot of experience working on big games such as retail and private servers for WoW, Baldur's Gate, Diablo, Minecraft, Zelda, OSRS, Mount and Blade, Civilization, WoT, War Thunder, and more shooters and big games but I mainly work with RPGs and Military Equipment and some Racing / flight / minigames games too: https://www.deviantart.com/withinamnesia/gallery + 
![All Hail To The King Baby!](https://github.com/devloglogan/MultiplayerFPSTutorial/assets/86871191/a5f48a27-fe0c-4d78-82a4-da6ec3627668) +
https://www.deviantart.com/withinamnesia/art/Game-Master-Veldryn-858651305 + https://www.deviantart.com/withinamnesia/gallery/75508504/catacombs-of-the-screaming-shadow + https://www.deviantart.com/withinamnesia/art/Long-Sword-3-Varscona-Arms-and-Armour-Emporium-770141205 + https://www.deviantart.com/withinamnesia/gallery/51118284/baldur-s-gate-path-of-the-lost-odyssey +  https://www.deviantart.com/withinamnesia/art/7TP-75-mm-wz-97-4-709711208 + https://www.deviantart.com/withinamnesia/gallery/50390205/b-o-w-n-3ds- + https://www.deviantart.com/withinamnesia/art/The-Jewelled-Eye-of-AGABAL-Jeweyel-Level-800-915001367 + https://www.deviantart.com/withinamnesia/gallery/64014697/agabal-r-p-g-project + https://www.deviantart.com/withinamnesia/gallery/52155361/concept-art-drawings + https://www.wowhead.com/item=118080/admiral-taylors-greatsword + https://www.deviantart.com/withinamnesia/art/Greatsword-of-Omen-3D-Model-Blender-2-79-871967906 (I am also a heavy duty mechanic for heavy equipment and I work on basically tanks. I have business experience operating a cedar salvage and milling corporation. I build houses and develop land from scratch too. I love learning and reading and writing history and I really love world building. These are some of the extra details that may help share a bit about who I am. I love creating massive multiplayer online role playing games and anything like most big games the most though lol.)
Where may I properly reach / contact / communicate? What should be done? What are your thoughts, feelings and suggestions? All feedback is welcome.
Update: Here is a completed example for DevLogLogan's Godot 4 - RPG Inventory System From Scratch tutorial for anyone to learn from and test. It is a masterful tutorial and I it took myself days to code by hand everything as an exact working copy for the community to learn from! I learn a lot about coding for Godot 4.2.1.NET+.

Does anyone have any free time to look at the code for this RPG Inventory from scratch tutorial and see how it can be translated / implemented with the Blockygame multiplayer demonstration? What should be done? What are your thoughts and suggestions? All feedback is welcome.
https://github.com/WithinAmnesia/ARPG/blob/ARPG-Infinite-Worlds/DevLogLogan%20RPG%20Inventory.zip
Here is the Blockygame demo too it needs the Godot_Voxel engine module to work: https://github.com/WithinAmnesia/ARPG/blob/ARPG-Infinite-Worlds/Infinite_Worlds_V.000.006.1.zip

**Comment by devloglogan** [comment]
This is not the place to inquire on such things. Best of luck on your project!
