### ISSUE TITLE
RPC syntax error in Player.gd

### ISSUE THREAD

**Issue by testman42** [devloglogan/MultiplayerFPSTutorial#2]
Something probably changed between version that was used to write this and Godot 4 beta 16.

But now editor shows errors on lines [73](https://github.com/devloglogan/MultiplayerFPSTutorial/blob/main/Player.gd#L73) and [80](https://github.com/devloglogan/MultiplayerFPSTutorial/blob/main/Player.gd#L80) in Player.gd.
those being `@rpc(call_local)` and `@rpc(any_peer)`.

Error being 
> Identified "call_local" not declared in the current scope

same for `any_peer`

Or is this a Godot editor issue and should be reported in their issue tracker?

**Comment by devloglogan** [comment]
Unfortunate that these syntax changes happened, but that's the risk of making these tutorials while still in beta I suppose. :)

I will fix this in the repo and pin a YT comment with the update. Thanks!

**Comment by devloglogan** [comment]
Fixed. As of beta 16 (I believe), rpc args are now passed as strings.
