### ISSUE TITLE
Issue when joining to host. Player not created when address is filled in

### ISSUE THREAD

**Issue by jonandrewdavis** [devloglogan/MultiplayerFPSTutorial#4]
First off, thank you for the incredible YouTube video & tutorial. Insanely high quality & very helpful.

I'm having issues joining when providing an address.

To reproduce my issue:

- Clone your project, https://github.com/devloglogan/MultiplayerFPSTutorial
- Import into Godot (Using beta-17)
- Run in debug mode with two instances
- Host on one
- Retrieve your IP from the console, or use https://icanhazip.com/
- Try to join by filling in the address: Paste your IP  
- Player is not created, but "seems" to be connected??

Some additional info: 
- Everything in your project works well, if you do not fill out address. `localhost`. It works great✅, your project and my fork.

Maybe there's a simple networking reason for this, but when joining, this isn't resulting in a `add_player` either place.  
https://github.com/devloglogan/MultiplayerFPSTutorial/blob/d858d77b4a2e9f4d70245e771fe2ddcbe8449d95/world.gd#L35

- Things get tough to debug. The Menu hides & server nor client create the peer..
- My issue occurs when hosting and joining across 2 computers in my house, or when serving headless on AWS [with these instructions](https://urodelagames.github.io/2022/04/19/setting-up-godot-server-on-aws/). The AWS set up works great for 3.5 multiplayer, which is very different, but uses the same ports & networking set up... so I believe I have ports open correctly, firewalls disabled, etc.

My code is [located here](https://github.com/jonandrewdavis/warp-world). 

![Screenshot 2023-02-04 121047](https://user-images.githubusercontent.com/6545465/216780384-8d19d28b-a658-4d3f-ae35-853ba5b64f83.jpg)

Thank you for any tips or suggestions you may have. I may need to rollback to an earlier version and set it up to see if it's an issue with the latest version.

**Comment by devloglogan** [comment]
The same issue arises for me when trying to connect two users on the same local network. I connected one of them to a cellular data hotspot instead and it was then able to connect just fine. I'm not actually sure if, when using UPNP, clients on the local network should be able to join using the external ip address. If they shouldn't be able to, maybe it's possible to build in some extra logic so local clients could join as well.

As for the headless AWS server, that is untraveled territory for me at the time being so I can't say anything about it.

I'll try to carve some time out soon to look into these further. Thanks for opening the issue!

**Comment by jonandrewdavis** [comment]
> I connected one of them to a cellular data hotspot instead and it was then able to connect just fine

Hmm yeah, that's promising. Indicates everything works & it's a network issue on my part.

> UPNP, using the external ip address

I tried a lot of different ways, including removing the UPNP which I thought would just run it on the box, then be accessible. im not sure what removing the UPNP call actually does though,. 

I'll do some more testing because it sounds like there's a network issue on my end or in the very least a confusion in my understanding. lol.

**Comment by jonandrewdavis** [comment]
Good evening. I tested some more using a few projects... I think things are mostly okay.

It turns out I was simply not running the project correctly in the cloud. Local UPNP may still be why it didn't work across 2 computers in my home... yet to do that debugging

With this guide I was able to convert a different project, pass in an arg to detect if I should start the server : https://www.youtube.com/watch?v=Xtg3qkLe2YA
And everything works against AWS.

Pictured are 3 clients running well connected to an EC2 micro in AWS. 

Slightly different project, but I think I can get yours working & mine with a little more time. 

![working](https://user-images.githubusercontent.com/6545465/217120986-6106475b-aad7-4822-a35d-a58b7039b1a2.jpg)

Sorry for the scattered debugging, I'm just new to this and also not applying a ton of rigor in my spare time. Feel free to close.

**Comment by jonandrewdavis** [comment]
And here's your project, featuring a standoff between 3 players.

- Server on EC2 (debugging in the background), now properly running
- client
- client

![image](https://user-images.githubusercontent.com/6545465/217123504-8bca8e85-a6fa-41de-91f3-f372e8e22ee4.png)

**Comment by jonandrewdavis** [comment]
Closing, as I think everything's working as intended. Thanks for the extra debug cycle.

**Comment by devloglogan** [comment]
I am glad you were able to resolve your cloud issues, very cool! I had reached out to a more networking-experienced person and, from what I've heard in casual conversation, it seems to be expected that UPNP wouldn't work with local network clients. Down the road I may make an addendum to this tutorial to cover this use case, thanks for bringing it to my attention!

No worries at all on the scattered debugging, happy you found any use at all out of the project. :)
