### ISSUE TITLE
cannot run directy in Godot 4.0 stable

### ISSUE THREAD

**Issue by GLITCHER4O4** [devloglogan/MultiplayerFPSTutorial#7]
I am having trouble to run this project in _godot 4.0_.It showing error in **func upnp_setup()** ,please fix this

**Comment by Bump-Dev** [comment]
I don't know if this is related but I am getting invalid gateway error in godot 4.0.

**Comment by devloglogan** [comment]
Unfortunately addressing these errors and the shortcomings of UPnP here are beyond the scope of the tutorial. The project does currently function on the latest version as intended. Common barriers include: not using a router, not having an IPv4 address, adding a client to a server that is hosted on the same router. You will have to explore other networking options if you bump into these problems.
